
public class EjerciciosEstructurasEnlazadas {
	
	public static void main(String...strings) {
		EE<Integer> e1 = new EE<Integer>();
		EE<Integer> e2 = new EE<Integer>();
		e1.combine(e2);
		System.out.println("Combinadas vacías");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
		e1.agregaFinal(1);
		e1.combine(e2);
		System.out.println("Combinadas segunda vacía");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
		e1.quitaUltimo();
		e2.agregaFinal(1);
		e1.combine(e2);
		System.out.println("Combinadas primera vacía");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
		e1.agregaFinal(2);
		e2.agregaFinal(2);
		e1.agregaFinal(3);
		e2.agregaFinal(3);
		e1.agregaFinal(4);
		e2.agregaFinal(4);
		e1.combine(e2);
		System.out.println("Combinadas mismos elementos");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
		e1.eliminaTodosRepetidosOrdenado();
		e1.agregaFinal(6);
		e1.agregaFinal(7);
		e1.combine(e2);
		System.out.println("Combinadas primera con más elementos");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
		e1.eliminaTodosRepetidosOrdenado();
		e1.quitaUltimo();
		e1.quitaUltimo();
		e2.agregaFinal(6);
		e2.agregaFinal(7);
		e1.combineNN(e2);
		System.out.println("Combinadas segunda con más elementos");
		System.out.println(e1);
		System.out.println("-");
		System.out.println(e2);
		System.out.println("----------------");
//		System.out.println(e1.eliminaTodosRepetidosOrdenado());
//		System.out.println("Despues de eliminar todos ordenado con la lista vacía: ");
//		System.out.println(e1);
//		e1.agregaFinal(1);
//		e1.agregaFinal(1);
//		e1.agregaFinal(1);
//		e1.agregaFinal(2);
//		e1.agregaFinal(2);
//		e1.agregaFinal(2);
//		e1.agregaFinal(8);
//		e1.agregaFinal(8);
//		e1.agregaFinal(8);
//		e1.agregaFinal(0);
//		e1.agregaFinal(0);
//		e1.agregaFinal(10);
//		e1.agregaFinal(12);
//		e1.agregaFinal(12);
//		e1.agregaFinal(12);
//		System.out.println(e1.eliminaTodosRepetidosOrdenado());
//		System.out.println("Despues de eliminar todos ordenado: ");
//		System.out.println(e1);
//		System.out.println(e1.eliminaTodosRepetidosDesordenado());
//		System.out.println("Despues de eliminar todos desordenado con la lista vacía: ");
//		System.out.println(e1);
//		e1.agregaFinal(1);
//		e1.agregaFinal(3);
//		e1.agregaFinal(7);
//		e1.agregaFinal(4);
//		e1.agregaFinal(2);
//		e1.agregaFinal(9);
//		e1.agregaFinal(7);
//		e1.agregaFinal(1);
//		e1.agregaFinal(9);
//		e1.agregaFinal(4);
//		e1.agregaFinal(2);
//		e1.agregaFinal(3);
//		e1.agregaFinal(3);
//		e1.agregaFinal(14);
//		e1.agregaFinal(7);
//		System.out.println(e1.eliminaTodosRepetidosDesordenado());
//		System.out.println("Despues de eliminar todos desordenado: ");
//		System.out.println(e1); //Debe dar 8 y escribir 1 9 4 2 3 14 7
	}

}
